# docker-compose.yml
version: '3.8'

# Definição dos serviços que compõem a aplicação
services:

  # --- Serviço Redis ---
  redis:
    image: redis:7.0.11-alpine
    container_name: smarttask-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - smarttask-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3

  # --- Serviço da API FastAPI ---
  api:
    container_name: smarttask-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - smarttask-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # --- Serviço do Worker ARQ ---
  worker:
    container_name: smarttask-worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - smarttask-net
    environment:
      - REDIS_HOST=smarttask-redis
    command: arq app.worker.WorkerSettings

# --- Definição de Redes ---
networks:
  smarttask-net:                 
    driver: bridge                

# --- Definição de Volumes ---
volumes:
  redis_data:
    driver: local                  